In [ ]:
 import pandas as pd
import numpy as np
info = np.array(['P','A','N','D','A','S'])
a= pd.Series(info)
print(a
      )


0    P
1    A
2    N
3    D
4    A
5    S
dtype: object


In [ ]:
import pandas as pd
# a list of strings
x=['python','Pandas']
#Calling DataFrame constructor on list
df= pd.DataFrame(x)
print(df)

        0
0  python
1  Pandas


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
emp =['Aman','Gagan','Rahul','Parul','william']
id= [543,102,321,109,104]
emp_series =pd.Series(emp)
id_series = pd.Series(id)
frame = {'Emp': emp_series,'ID': id_series}
result =pd.DataFrame(frame)
print(result)

       Emp   ID
0     Aman  543
1    Gagan  102
2    Rahul  321
3    Parul  109
4  william  104


In [ ]:
# importing the pandas library
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
#importing thr pandas library
import pandas as pd
# a list of strings
x =['Python','Pandas']
# Calling DataFrame constructor on list
df = pd.DataFrame(x)
print(df)

        0
0  Python
1  Pandas


In [ ]:
import pandas as pd
import numpy as np
a =pd.Series(['Java','c','C++','np.nan'])
a.map({'Java':'Core'})


0    Core
1     NaN
2     NaN
3     NaN
dtype: object

In [10]:
# import the "array" for demonstarating array operations
import array
#initializing an array with array values and signed integers
arr = array.array('l',[2,4,6,8,10,12])
#print the original array
print ("New created array:",end="")
for l in range (0,5):
  print(arr[l],end=" ")
  print ("\r")

New created array:2 
4 
6 
8 
10 


In [18]:
#importing pandas as pd
import pandas as pd
# dictonary of lists
dict ={'name':["Parul","Willian","Taniya","Phill","Parker"],'age':["28","23","31","43","25"]}

df = pd.DataFrame(dict,index =[True,True,False,True,False])
print(df)
print("\n accessing the name and age only true value :")
print(df.loc[True])
print("\n accessing the name and age only false value:")
print(df.loc[False])

          name age
True     Parul  28
True   Willian  23
False   Taniya  31
True     Phill  43
False   Parker  25

 accessing the name and age only true value :
         name age
True    Parul  28
True  Willian  23
True    Phill  43

 accessing the name and age only false value:
         name age
False  Taniya  31
False  Parker  25


In [21]:
import numpy as np
arr = np.arange(20)
print("The Original array is:\n,arr")
# shape array with 2 rows and 8 columns
arr =np.arange(20).reshape(2,10)
print("\nreshapedarray:\n",arr)
#shape array with 2 rows and 10 columns
arr = np.arange(20).reshape(2,10)
print("\nreshaped array:\n",arr)


The Original array is:
,arr

reshapedarray:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

reshaped array:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
